function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 23-Sep-2019 21:31:07

% Create figure
figure1 = figure('Color',[1 1 1]);
colormap(lines);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'ZDataSource','','Color',[0 0 1]);

% Create ylabel
ylabel({'F(w)'});

% Create xlabel
xlabel({'w'});

% Create title
title({'Problema 2'},'BackgroundColor',[1 1 1],...
    'EdgeColor',[0 0.447058826684952 0.74117648601532],...
    'FontAngle','italic',...
    'FontName','Ink Free');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Color',[0.941176474094391 0.941176474094391 0.941176474094391],...
    'FontSize',12,'XColor',[0 0 0],'YColor',[0 0 0],'ZColor',[0 0 0]);
